### ISSUE TITLE
Chrome (29) the layout is off causing premature wrapping

### ISSUE THREAD

**Issue by jafin** [kalyan02/flowr-js#2]
In Chrome (29) the column width changes after the images are loaded. On my box it appears to shrink by 15px.  

Setting 'maxWidth' : this.width()-15  makes it work in Chrome and looks ok in FF but is a crappy hack.

**Comment by kalyan02** [comment]
Seems like the scrollbar is causing the width to jump. I will look into it. Thanks for reporting.

**Comment by kalyan02** [comment]
@jafin I pushed a fix for issue #3 which fixes this too.

**Comment by ralsina** [comment]
I still see this. On Chromium I always get one image wrapped on every row, unless I do something like 

```
var fullScaleWidth = settings.maxWidth - requiredPadding() - 10;
```
